[package]
name = "xtunnel"
version = "0.1.0"
authors = ["Light Lin <lxrite@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
tokio = { version = "1.23.0", features = ["full"] }
